import type { Metadata } from "next";
import { ReactElement, ReactNode } from "react";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export type LayoutProps = {
  children: ReactNode
}

const RootLayout = ({ children }: LayoutProps): ReactElement => {
  console.log(children)
  return (
    <html lang="en">
      <body className={inter.className}>
        Testing
      </body>
    </html>
  );
}

export default RootLayout;