import type { Metadata } from "next";
import { ReactNode } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export type LayoutProps = {
  children: ReactNode
}

const RootLayout = async ({ children }: LayoutProps) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <div className="bottom-0 col-span-2">
          <Footer/>
        </div>
      </body>

    </html>
  );
}

export default RootLayout;